### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by kjkpoi** [ms1995/ella-customized#2]
Thanks for making mutlidex version of ella.

I have a trouble with building your ella.

Please help me. I put my execution log.

Input:
ant

Output:

BUILD FAILED
/home/kjkpoi/Documents/ella-customized/build.xml:10: The following error occurred while executing this line:
/home/kjkpoi/Documents/ella-customized/runtime/build.xml:21: java.lang.RuntimeException: The executable 'android' is not in the path
	at GuessDefaultSettingsTask.findAndroidSDKPath(GuessDefaultSettingsTask.java:46)
	at GuessDefaultSettingsTask.execute(GuessDefaultSettingsTask.java:11)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

**Comment by kjkpoi** [comment]
I solved the above problem, but I find new problem with multidex apk.

error logs

Exception in thread "main" org.jf.util.ExceptionWithContext: debug info items must have non-decreasing code addresses                                                                   
8344   at org.jf.dexlib2.writer.DebugWriter.writeLineNumber(DebugWriter.java:111)
8345   at org.jf.dexlib2.writer.pool.ClassPool.writeDebugItem(ClassPool.java:506)
8346   at org.jf.dexlib2.writer.DexWriter.writeDebugItem(DexWriter.java:859)
8347   at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:767)
8348   at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:222)
8349   at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:200)
8350   at org.jf.dexlib2.writer.pool.DexPool.writeTo(DexPool.java:99)
8351   at org.jf.dexlib2.DexFileFactory.writeDexFile(DexFileFactory.java:120)
8352   at com.apposcopy.ella.Instrument.instrument(Instrument.java:139)
8353   at com.apposcopy.ella.Instrument.instrument(Instrument.java:53)
8354   at com.apposcopy.ella.Main.main(Main.java:42)

**Comment by kjkpoi** [comment]
I add more logs. If you solve it, it will be great for me.

Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException                                                                                                  
542   at com.apposcopy.ella.Instrument.mergeEllaRuntime(Instrument.java:411)
543   at com.apposcopy.ella.Instrument.instrument(Instrument.java:59)
544   at com.apposcopy.ella.Instrument.instrument(Instrument.java:53)
545   at com.apposcopy.ella.Main.main(Main.java:42)
546 Caused by: java.lang.reflect.InvocationTargetException
547   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
548   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
549   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
550   at java.lang.reflect.Method.invoke(Method.java:498)
551   at com.apposcopy.ella.Instrument.mergeEllaRuntime(Instrument.java:402)
552   ... 3 more
553 Caused by: java.io.FileNotFoundException: /home/kjkpoi/ella-customized/bin/ella-wrappers/EllaWrapper2.dex (No such file or directory)
554   at java.io.FileInputStream.open0(Native Method)
555   at java.io.FileInputStream.open(FileInputStream.java:195)
556   at java.io.FileInputStream.<init>(FileInputStream.java:138)
557   at com.android.dex.Dex.<init>(Dex.java:119)
558   at com.android.dx.merge.DexMerger.main(DexMerger.java:1189)
559   ... 8 more

**Comment by ms1995** [comment]
You will need to run `gen-ella-wrappers.py` before instrumenting MultiDex APKs. Please see `Extra steps for Multidex support` section in README.

**Comment by ThornJansen** [comment]
> Thanks for making mutlidex version of ella.
> 
> I have a trouble with building your ella.
> 
> Please help me. I put my execution log.
> 
> Input:
> ant
> 
> Output:
> 
> BUILD FAILED
> /home/kjkpoi/Documents/ella-customized/build.xml:10: The following error occurred while executing this line:
> /home/kjkpoi/Documents/ella-customized/runtime/build.xml:21: java.lang.RuntimeException: The executable 'android' is not in the path
> at GuessDefaultSettingsTask.findAndroidSDKPath(GuessDefaultSettingsTask.java:46)
> at GuessDefaultSettingsTask.execute(GuessDefaultSettingsTask.java:11)
> at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
> at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> at org.apache.tools.ant.Task.perform(Task.java:350)
> at org.apache.tools.ant.Target.execute(Target.java:449)
> at org.apache.tools.ant.Target.performTasks(Target.java:470)
> at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
> at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
> at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
> at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
> at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
> at org.apache.tools.ant.Task.perform(Task.java:350)
> at org.apache.tools.ant.Target.execute(Target.java:449)
> at org.apache.tools.ant.Target.performTasks(Target.java:470)
> at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
> at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
> at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
> at org.apache.tools.ant.Main.runBuild(Main.java:834)
> at org.apache.tools.ant.Main.startAnt(Main.java:223)
> at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
> at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)

Hi @kjkpoi,

I am trying to work with Ella as well and I am running into the same issue. Could you perhaps indicate how you managed to solve your issue? Thank you for your time.

Kind regards,

Thorn
