### ISSUE TITLE
Exception in thread "main" org.jf.util.ExceptionWithContext: /tmp/inputclasses1647275339239588736.dex

### ISSUE THREAD

**Issue by wangyan841331749** [ms1995/ella-customized#3]
hi, when i execute the comman: ella.sh i <path-to-apk>, i got the error:
Exception in thread "main" org.jf.util.ExceptionWithContext: /tmp/inputclasses1647275339239588736.dex is not an apk, dex file or odex file.
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:116)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:49)
	at com.apposcopy.app.App.<init>(App.java:46)
	at com.apposcopy.app.App.readApp(App.java:51)
	at com.apposcopy.ella.Main.main(Main.java:28)

could you tell me how to resolve the problem, thank you very much! i dont know why it has the error.

**Comment by ms1995** [comment]
If you’re sure that the APK itself has no issue, then likely there’s some issue in the dexlib2 library (under `instrument/libs`). Consider upgrading to the latest version from `https://mvnrepository.com/artifact/org.smali/dexlib2`.
