### ISSUE TITLE
EllaLauncher Error

### ISSUE THREAD

**Issue by melisMirza** [ms1995/ella-customized#4]
Hi,
When I run the ella.sh i command, I receive the following error;

The ella server must be run on 127.0.0.1 (explicitly specified in ella settings)
Standard output and error is redirected to /home/mmm/Documents/SWE599/ella-customized/ella-out/_home_mmm_Documents_SWE599_apks_com.jetstartgames.chess_2.7.9-74_minAPI16(nodpi)_apkmirror.com.apk/log.txt
Exception in thread "main" java.lang.Error: Error occurred while instrumenting. exit code is 1
	at com.apposcopy.ella.EllaLauncher.instrument(EllaLauncher.java:259)
	at com.apposcopy.ella.EllaLauncher.main(EllaLauncher.java:23)

And the log file reports:

[Fatal Error] stamp_android_manifest2779795146495251942.tmp:1:1: Content is not allowed in prolog.
Exception in thread "main" java.lang.Error: org.xml.sax.SAXParseException; systemId: file:/tmp/stamp_android_manifest2779795146495251942.tmp; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.apposcopy.app.ParseManifest.<init>(ParseManifest.java:63)
	at com.apposcopy.app.App.readApp(App.java:54)
	at com.apposcopy.ella.Main.main(Main.java:28)
Caused by: org.xml.sax.SAXParseException; systemId: file:/tmp/stamp_android_manifest2779795146495251942.tmp; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
	at com.apposcopy.app.ParseManifest.<init>(ParseManifest.java:35)
	... 2 more

What may be the issue? 

Thanks in advance.

**Comment by ms1995** [comment]
This seems to be caused by Apktool. Please consider upgrading apktool.jar to the latest version.

**Comment by melisMirza** [comment]
Thanks for your reply. 
I upgraded apktool from 2.4.2 to 2.5.0 but unfortunately the problem persists. Java and Android SDK versions also comply with the requirements. I tried with different and verified APKs, all having this same issue. Are there any other components to consider?

**Comment by ms1995** [comment]
Can you try depackaging the APKs using Apktool’s command line and see whether AndroidManifest.xml can be properly decoded?

**Comment by melisMirza** [comment]
it seems apktool is correctly decoding the package. I validated the Android manifest xml file as well and it doesn't have any errors.

**Comment by Dunamo** [comment]
Hi,
I met the similar problem when i run ella.sh i command. receive the following error

I upgraded apktool.jar from 2.3.1 to 2.5.0 find the same problems to melisMirza

The ella server must be run on 192.168.182.132 (explicitly specified in ella settings)
Standard output and error is redirected to /home/jdd/Code/ella-customized/ella-out/_home_jdd_AUT_droidbotApp.apk/log.txt
Exception in thread "main" java.lang.Error: Error occurred while instrumenting. exit code is 1
	at com.apposcopy.ella.EllaLauncher.instrument(EllaLauncher.java:259)
	at com.apposcopy.ella.EllaLauncher.main(EllaLauncher.java:23)

the log profile is :
[Fatal Error] stamp_android_manifest3760717262251367522.tmp:1:1: Content is not allowed in prolog.
Exception in thread "main" java.lang.Error: org.xml.sax.SAXParseException; systemId: file:/tmp/stamp_android_manifest3760717262251367522.tmp; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.apposcopy.app.ParseManifest.<init>(ParseManifest.java:63)
	at com.apposcopy.app.App.readApp(App.java:54)
	at com.apposcopy.ella.Main.main(Main.java:28)
Caused by: org.xml.sax.SAXParseException; systemId: file:/tmp/stamp_android_manifest3760717262251367522.tmp; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at com.apposcopy.app.ParseManifest.<init>(ParseManifest.java:35)
	... 2 more


Thank you

**Comment by ms1995** [comment]
Frankly speaking, it's been years since I used this tool, and I'm not even the author of the tool, it's difficult to recall all the implementation details. On the other hand, Android has been changing, and it's possible that some new elements in APKs are not recognized by this aged tool (I was using this tool with Android 4.4-compatible APKs).

While I may have some time to look into issues related to this tool later, I would suggest you to look into them by yourselves, given that you already have the necessary environment to reproduce the issues, and I currently don't have more knowledge of this tool compared with you.

Please feel free to share your experiences with this tool here or at the original author's repo.

**Comment by Dunamo** [comment]
Thank you for your reply.
________________________________
发件人: ms1995 ***@***.***>
发送时间: 2021年6月15日 14:45
收件人: ms1995/ella-customized ***@***.***>
抄送: Dunamo ***@***.***>; Comment ***@***.***>
主题: Re: [ms1995/ella-customized] EllaLauncher Error (#4)


Closed #4<https://github.com/ms1995/ella-customized/issues/4>.

―

**Comment by maryammsd** [comment]
Does anyone find a solution for this problem? I am encountering the same problem
